### ISSUE TITLE
关于HMAC计算并加密成Base64的建议

### ISSUE THREAD

**Issue by lilonghe** [cnxh/1024tools#1]
开始我是在做OAuth验证的时候找到这个网站，后来发现 HMAC-SHA1 -> Base64 得到的签名始终对不上号。
于是，我用C#自己也实现了一个
``` csharp
byte[] hashBytes = hmacsha1.ComputeHash(dataBuffer);
string sig = Convert.ToBase64String(hashBytes);
```
在这一步的时候发现了不同
您的做法似乎是加密后转成字符串然后再加密成Base64字符串?
建议可以加上一个hash -> base64 的输出值

**Comment by cnxh** [comment]
谢谢反馈，  马上加上。 ^_^

**Comment by lilonghe** [comment]
cool
