### ISSUE TITLE
试图部署代码可是提示没有数据库

### ISSUE THREAD

**Issue by DrEastex** [cnxh/1024tools#2]
Hi，你的项目真的很牛
我试着在自己的环境上面部署了一下
从log看提示的是没有指定的表（因为数据库是我自己建立的）
请问该数据库通过什么方式可以获取到呢？多谢。

**Comment by cnxh** [comment]
你执行下 `php artisan migrate `应该能导入数据库结构
数据库结构已经放到database/migrations目录下了

**Comment by DrEastex** [comment]
多谢！！！
