### ISSUE TITLE
请求特性：输入使用 Base64 表示的 HMAC 密钥

### ISSUE THREAD

**Issue by LionNatsu** [cnxh/1024tools#5]
或许可以在密钥输入框旁加入一个开关（比如单选框，复选框，下拉列表，状态锁存开关，……）。
除了 Base64 也可以考虑提供 Hex 编码。
可参考 [JWT, JSON Web Tokens](https://jwt.io/) 的 Debugger / Decoded 参数中的 HMAC

**Comment by cnxh** [comment]
是需要支持输入 base64或者hex编码后的密钥吗？  hmac计算的时候还是按编码前的密钥计算是吧？

**Comment by LionNatsu** [comment]
打个比方的话……就像这样：

```
密钥
[___________________]    [ ] Base64 encoded
```

**Comment by LionNatsu** [comment]
考虑这样一个情景：某一系统为了安全，采用了 SHA256 的 HMAC，那么为了尽可能达到充分的安全程度，初次启动服务器的时候生成了一个长度为 256 位（也就是 32 个字符）的随机字节串（虽然可以说是字符，但我想说明这里一般不是可打印的）存放到了某一个文件里。

那么现在一个维护者，可能想直接手动进行一次演算，那么可以读取这个文件，在 Linux 下可能会用 `cat hmac.key | base64` 这样的命令来显示，也有可能是 `cat hmac.key | hexdump`，但总之不能是 `cat hmac.key` 因为屏幕上没法输出这一堆乱码。

**Comment by cnxh** [comment]
了解了， 赞！
