### ISSUE TITLE
1024tools.com 载入遇到问题

### ISSUE THREAD

**Issue by Frank-Dell** [cnxh/1024tools#9]
您好，最近发现 1024tools.com 的载入会卡在 “正在等待 statics.1024tools.com 的响应…” 这一步，请求解决此问题，非常感谢。

**Comment by cnxh** [comment]
您好，谢谢反馈。刚已修改，请帮忙看看现在是否正常了。

statics.1024tools.com 使用的aliyun的cdn，今天我这边也发现打开特别慢，已经切换掉暂时不使用cdn，相关改动在 [这里](https://github.com/cnxh/1024tools/commit/edc54e7a05b46c2757fbd410d9bbd335fd939a0f)

**Comment by Frank-Dell** [comment]
您好，我这里测试已经正常了。
谢谢您。
